language: generic 
sudo: required
services: 
    - docker

before_install:
    - docker build -t luizloja/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true luizloja/react-test npm run test  -- --coverage  

after_success:
    - docker build -t luizloja/complex-client ./client 
    - docker build -t luizloja/complex-nginx ./nginx
    - docker build -t luizloja/complex-server ./server
    - docker build -t luizloja/complex-worker ./worker

# Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
    - docker push luizloja/complex-client
    - docker push luizloja/complex-nginx
    - docker push luizloja/complex-server
    - docker push luizloja/complex-worker



       